### PR TITLE
New: Make HttpClient timeout configurable

### PR DESCRIPTION
**Pull request by mheap**

### CODE REVIEW

**Comment by ollieparsley** [comment]
Are there any tests? :p

**Comment by mheap** [comment]
Zero! I did search but there's no test harness for HttpClient

**Comment by ollieparsley** [comment]
Fair do's :)

**Comment by stuartherbert** [comment]
Hello!

Erm - there's actually 2 timeout values used internally in HttpLib:

* the timeout on initial connection
* the timeout when reading from the connection

This PR has added a generic 'setTimeout()' which is only used to set the connection timeout.

Any chance you could update this?

* HttpClientRequest::getTimeout() to be getConnectionTimeout()
* HttpClientRequest::setTimeout() to be setConnectionTimeout()
* add HttpClientRequest::getReadTimeout() and HttpClientRequest::setReadTimeout() too
* use both in HttpClientConnection

Similarly, we'll need to update the changes made to the HTTP module in Storyplayer.

Many thanks,
Stu

**Comment by mheap** [comment]
New PR submitted at https://github.com/datasift/ms-lib-stone/pull/14 - my
mistake trying to fix something quickly without reading the code properly.
Thanks for the heads up

**Pull request merged**
